networks:
  activity-punch-system-backend-net:
    driver: bridge

services:
  app:
    # build: ..
    image: activity-punch-2026:latest
    container_name: activity-punch-system-backend-app
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./log:/log
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - activity-punch-system-backend-net

  mysql:
    image: mysql:8.0
    container_name: activity-punch-system-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0nline@seal
      MYSQL_DATABASE: activity-punch-system-backend
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    privileged: true
    restart: always
    ports:
      - 8081:3306
    networks:
      - activity-punch-system-backend-net

  redis:
    image: redis:7.0
    container_name: activity-punch-system-redis
    command: --requirepass 0nline@seal
    environment:
      TZ: Asia/Shanghai
    privileged: true
    restart: always
    networks:
      - activity-punch-system-backend-net

#  watchtower:
#    image: containrrr/watchtower
#    container_name: activity-punch-system-backend-watchtower
#    command: --interval 5
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # 需要将 Docker 的 sock 映射进去以控制 Docker
#    restart: always
#    networks:
#      - activity-punch-system-backend-net